/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_internal_AlliancesJni */

#ifndef _Included_app_internal_AlliancesJnipp
#define _Included_app_internal_AlliancesJnipp
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     app_internal_AlliancesJni
 * Method:    getVersionpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_internal_AlliancesJni_getVersionpp(JNIEnv* env, jclass thiz);


#ifdef __cplusplus
}
#endif
#endif